version: '3.3'
services:
  mongodb_server:
    container_name: mongodb_server
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - '/Users/radhakantaghosh/Office/BaseWorkSpace/JavaSpace/mongodb-springboot-demo/mongod.conf:/etc/mongod.conf'
      - '/Users/radhakantaghosh/Office/Install/mongodb:/data/db'
    ports:
      - '37017:27017'